sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
before_install:
  - gem update bundler
script:
  - bundle install
  - bundle exec rake
env:
  matrix:
    - ENABLE_MYSQL_AWESOME=0
    - ENABLE_MYSQL_AWESOME=1
    - POSTGRESQL=1
addons:
  postgresql: "9.4"
