language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1
script:
  - bundle install
  - bundle exec rake
env:
  matrix:
    - ENABLE_MYSQL_AWESOME=0
    - ENABLE_MYSQL_AWESOME=1
    - POSTGRESQL=1
addons:
  postgresql: "9.3"
