# Site settings
title: Ridgepole
email: sgwr_dts@yahoo.co.jp
description: "Ridgepole is a tool to manage DB schema. It defines DB schema using Rails DSL, and updates DB schema according to DSL. (like Chef/Puppet)"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ridgepole.codenize.tools/"
github_url: "https://github.com/winebarrel/ridgepole"
twitter_username: sgwr_dts
github_username:  winebarrel
original_background_image_url: "https://www.flickr.com/photos/tanaka_juuyoh/8072950260/in/photolist-bbXXB-dinZah-diGxNo-dinYRA-diGxEL-di5wT6-dsGTkB-9ip2sc-9is7Lj-aithtp-dio27R-6dgTmr-98qwpW-e6FCFD-2225Qs-5PWaaJ-dth5pP-5sMyq7-5ZnB9m-9ip6gc-72zQgm-dth5zD-72zGou-6dgPyv-8rCKkj-fGDuN2-72wJxn-72vAmg-4tU5Yg-5ZRCnH-9ip9x4-9isd4N-9ip4hB-9ip56B-9ip7Ep-9is9sN-9isej3-9iseVw-9ipaAi-9ipbrg-hvqG76-4R75VJ-72ww94-JWodw-5HcYWb-72AFrs-72wmpT-72Aje5-72wMJk-72AzoS"
background_image_licence: "images/background.license"

# Build settings
markdown: kramdown
